---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Liz.
--- DateTime: 2020-5-20 21:38
---
---
require 'module/enum/PackageName'
require 'module/mainView/TestListItem'

UIExtensionManager = {}
UIExtensionManager.extensions = {
    [PackageName.Main] = {
        TestListItem = TestListItem,
        ImageTestView = ImageTestView
    }
}

UIExtensionManager.reg = function(pkgName,resName,cls)
    local itemUrl = UIPackage.GetItemURL(pkgName, resName)
    if itemUrl then
        print("开始注册",itemUrl,cls)
        fgui.register_extension(itemUrl,cls)
    else
        print("注册失败："..pkgName.."---"..resName)
    end
end

UIExtensionManager.register = function(pkgName)
    local extensions = UIExtensionManager.extensions[pkgName]
    if extensions then
        for resName,cls in pairs(extensions) do
            UIExtensionManager.reg(pkgName,resName,cls)
        end
    end
end