---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Liz.
--- DateTime: 2020-5-24 23:09
---
local view = fgui.extension_class(GComponent)
function view:ctor()
    print("图片测试")

    view.processBar = self:GetChild("progressBar")
    view.processBar.max = 100
    view.processBar.value = 0
    view.processBar:TweenValue(100,5)

    view.imgProcess = self:GetChild("n66")
    view.imgProcess.fillAmount = 0.5
end

ImageTestView = ImageTestView or view